In [0]:
import tensorflow as tf
import numpy as np

In [2]:
tf.InteractiveSession()

In [0]:
a = tf.zeros((2,2))
b = tf.ones((2,2))

In [4]:
b.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [5]:
tf.reduce_sum(b, reduction_indices=1).eval()

array([2., 2.], dtype=float32)

In [6]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [7]:
tf.reshape(a,(1,4)).eval()

array([[0., 0., 0., 0.]], dtype=float32)

In [8]:
tensor = tf.convert_to_tensor(np.random.normal(size=(2,3)))
print(tensor)

Tensor("Const:0", shape=(2, 3), dtype=float64)


In [9]:
print(tensor.eval())

[[-0.55204798  1.41455142  0.19563076]
 [-0.18881083  1.63823494 -0.24361949]]


In [10]:
tf.constant(np.random.normal(size=(5,1))).eval()

array([[1.67399084],
       [1.16746686],
       [1.01437425],
       [0.71627594],
       [0.17095476]])

In [11]:
w = tf.Variable(tf.ones(2,2), name='weights')
tf.global_variables_initializer().run()
w.eval()

array([1., 1.])

In [12]:
rw = tf.Variable(tf.random_normal((5,1)) , name='rweights')
tf.global_variables_initializer().run()
rw.eval()

array([[0.15052977],
       [0.1949292 ],
       [0.0118634 ],
       [1.893649  ],
       [1.4543025 ]], dtype=float32)

In [13]:
var_1 = tf.Variable(tf.zeros((6,1), dtype=tf.int64))
cte = tf.constant(np.random.randint(low = 0, high= 5, size=(6,1)))
add_op = tf.add(var_1 , cte)
upd_op = tf.assign(var_1, add_op)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for _ in range(5):
    sess.run(upd_op)
    print(sess.run(var_1))
    print('---')


[[1]
 [4]
 [1]
 [2]
 [3]
 [2]]
---
[[2]
 [8]
 [2]
 [4]
 [6]
 [4]]
---
[[ 3]
 [12]
 [ 3]
 [ 6]
 [ 9]
 [ 6]]
---
[[ 4]
 [16]
 [ 4]
 [ 8]
 [12]
 [ 8]]
---
[[ 5]
 [20]
 [ 5]
 [10]
 [15]
 [10]]
---


In [14]:
inp1 = tf.placeholder(dtype = tf.float32, shape = (1,2))
inp2 = tf.placeholder(dtype =tf.float32, shape=(2,1))
ip = tf.matmul(inp1,inp2)

with tf.Session() as sess:
  i1 = np.random.normal(size = (1,2))
  i2 = np.random.normal(size = (2,1))
  inner_prod = sess.run(ip, feed_dict={inp1:i1, inp2:i2})
  print(i1,'X', i2,'=',inner_prod)
  

[[-1.49637363  1.1253308 ]] X [[-1.7671446 ]
 [ 0.06228331]] = [[2.714398]]


In [0]:
x_ = tf.placeholder(tf.float32, shape=(4,2), name='x-input')
y_ = tf.placeholder(tf.float32, shape=(4,1), name='y-input')

In [0]:

w1 = tf.Variable(tf.random_normal((2,2)))
b1 = tf.Variable(tf.zeros((2)))

w1p = tf.Variable(tf.random_normal((2,2)))
b1p = tf.Variable(tf.zeros((2)))

w2 = tf.Variable(tf.random_normal((2,1)))
b2 = tf.Variable(tf.zeros((1)))

In [0]:
z1 = tf.matmul(x_,w1) +b1
a1 = tf.sigmoid(z1)
z1p = tf.matmul(a1,w1p) +b1p
a1p = tf.sigmoid(z1p)
z2 = tf.matmul(a1p,w2) + b2
a2 = tf.sigmoid(z2)

In [0]:

loss = -((y_* tf.log(a2)) +((1.0-y_)*tf.log(1.0-a2))) 
cost = tf.reduce_mean(loss) 

In [0]:
learning_rate = 0.1
op_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [0]:
XOR_X = [[0,0],[0,1],[1,0],[1,1]]
XOR_Y = [[0],[1],[1],[0]]

In [53]:
init = tf.global_variables_initializer()
sess = tf.Session()

sess.run(init)

for i in range(100000):
  sess.run(op_step, feed_dict={x_:XOR_X, y_:XOR_Y})

print('Final Prediction', sess.run(a2, feed_dict={x_: XOR_X, y_: XOR_Y}))
print('Final rounded Prediction', np.round(sess.run(a2, feed_dict={x_: XOR_X, y_: XOR_Y})))

Final Prediction [[8.1757782e-05]
 [9.9952805e-01]
 [9.9952757e-01]
 [1.3048465e-03]]
