In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
tf.InteractiveSession()

In [5]:
#initializing a cte tensor
tf.zeros(2)

<tf.Tensor 'zeros_1:0' shape=(2,) dtype=float32>

In [6]:
a = tf.zeros(2)
a.eval()

array([0., 0.], dtype=float32)

In [7]:
a = tf.zeros((2,3))
a.eval()

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [8]:
b = tf.ones((2,2,2))
b.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [9]:
b = tf.fill((2,2), value = 5.)
b.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [10]:
b = tf.constant(3.)
b.eval()

3.0

In [11]:
a = tf.random_normal((2,2), mean=0., stddev=1.)
a.eval()

array([[ 0.16546781,  0.3098498 ],
       [-0.07595156,  0.27224383]], dtype=float32)

In [12]:
a = tf.truncated_normal((2,2), mean=0., stddev=1.)
a.eval()

array([[-1.874403  , -0.51817507],
       [-1.2943332 , -0.13670994]], dtype=float32)

In [13]:
a = tf.random_uniform((2,2), minval=-2., maxval=2.)
a.eval()


array([[-0.80092525, -0.52423334],
       [ 0.00742435,  1.953063  ]], dtype=float32)

In [14]:
c = tf.ones((2,2))
d = tf.ones((2,2))
e = c + d
e.eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [15]:
f = 2*e
f.eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [16]:
c = tf.fill((2,2), value=2.)
d = tf.fill((2,2), value=7.)
e = c*d
e.eval()

array([[14., 14.],
       [14., 14.]], dtype=float32)

In [17]:
a = tf.eye(4)
a.eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [18]:
r = tf.range(1,5,1)
r.eval()

array([1, 2, 3, 4], dtype=int32)

In [19]:
d = tf.diag(r)
d.eval()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)

In [20]:
a = tf.ones((2,3))
a.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [21]:
at = tf.matrix_transpose(a)
at.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [22]:
a = tf.ones((2,3))
b = tf.ones((3,4))

c = tf.matmul(a,b)
c.eval()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

In [23]:
a = tf.ones((2,2), dtype=tf.int32)
a.eval()

array([[1, 1],
       [1, 1]], dtype=int32)

In [24]:
b = tf.to_float(a)
b.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [25]:
a = tf.ones(8)
a.eval()

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [26]:
b = tf.reshape(a, (4,2))
b.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [27]:
c = tf.reshape(a, (2,2,2))
c.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [28]:
a = tf.ones(2)
a.get_shape()

TensorShape([Dimension(2)])

In [29]:
b = tf.expand_dims(a, 0)
b.eval()

array([[1., 1.]], dtype=float32)

In [30]:
b.get_shape()

TensorShape([Dimension(1), Dimension(2)])

In [31]:
c = tf.expand_dims(a, 1)
c.eval()

array([[1.],
       [1.]], dtype=float32)

In [32]:
c.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
tf.get_default_graph()

In [34]:
tf.get_default_session()

In [38]:
sess = tf.Session()
a = tf.ones((2,3))
b = tf.diag(tf.range(0., 3.))
c = tf.matmul(a,b)
#sess.run(c)
c.eval(session=sess)

array([[0., 1., 2.],
       [0., 1., 2.]], dtype=float32)

In [39]:
#Variables
a = tf.Variable(tf.ones((2,2)))
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>

In [40]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
a.eval(session = sess)

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [41]:
sess.run(tf.assign(a, tf.zeros((2,2))))

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [43]:
sess.run(a.assign(tf.fill((2,2), value=3.)))

array([[3., 3.],
       [3., 3.]], dtype=float32)